name: API Compatibility

on:
  pull_request:
    branches: [ main, metrics ]
    paths-ignore:
    - '**.md'

jobs:
  build-test:
    runs-on: windows-latest
    env:
      CheckAPICompatibility: true
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release
