name: Linux

on:
  push:
    branches: [ main, metrics ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main, metrics ]
    paths-ignore:
    - '**.md'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [netcoreapp3.1,net5.0]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: dotnet build OpenTelemetry.proj --configuration Release

    - name: Test ${{ matrix.version }}
      run: dotnet test **/bin/**/${{ matrix.version }}/*.Tests.dll --configuration Release --no-build --logger:"console;verbosity=detailed"
