name: Windows

on:
  push:
    branches: [ main, metrics ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main, metrics ]
    paths-ignore:
    - '**.md'

jobs:
  build-docs-examples:
    runs-on: windows-latest

    strategy:
      matrix:
        version: [net461,net5.0]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: dotnet msbuild OpenTelemetry.proj -target:BuildDocsAndExamples -property:Configuration=Release

    - name: Test ${{ matrix.version }}
      run: dotnet test **\bin\**\${{ matrix.version }}\*Tests.dll --configuration Release --no-build --logger:"console;verbosity=detailed"
