name: Windows

on:
  pull_request:
    branches: [ main, metrics ]
    paths-ignore:
    - '**.md'

jobs:
  build-test:
    runs-on: windows-latest

    strategy:
      matrix:
        version: [net452,net46,net461,netcoreapp2.1,netcoreapp3.1,net5.0]

    steps:
    - uses: actions/checkout@v2

    - name: run where is sn
      shell: cmd
      run: where /R \ sn.exe

    - name: Disable SN
      run: .\build\disable_snv.ps1
      shell: powershell

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Disable SN
      run: .\build\disable_snv.ps1
      shell: powershell

    - name: Test ${{ matrix.version }}
      run: dotnet test **\bin\**\${{ matrix.version }}\*Tests.dll --configuration Release --no-build --logger:"console;verbosity=detailed"
